pfam_db: 'ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz'
refGTF_pa_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.primary_assembly.annotation.gtf.gz'
refGTF_comp_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.annotation.gtf.gz'
refGTF_basic_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.basic.annotation.gtf.gz'
refGFF3_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.basic.annotation.gff3.gz'
refPA_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/GRCh38.primary_assembly.genome.fa.gz'
refFasta_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.pc_transcripts.fa.gz'
refProtSeq_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.pc_translations.fa.gz'
salmon_version: 'salmon/0.11.0'
stringtie_version: 'stringtie/1.3.4d'
STAR_version: 'STAR/2.6.1c'
rmats_verson: 'rmats/4.0.2'
R_version: 'R/3.5.0'
TransDecoder_version: 'TransDecoder/5.0.1'
samtools_version: 'samtools/1.9'
gffcompare_version: 'gffcompare/0.10.5'
hmmer_version: 'hmmer/3.2.1'
crossmap_version: 'crossmap/0.2.7'
chain_file: 'ref/GRCh38_to_GRCh37.chain'
sampleFile: 'sampleTableV4.tsv'
tissueFile: 'ref/tissues.txt'
subtissueFile: 'ref/subtissues.txt'
fastq_path: '/data/swamyvs/autoRNAseq/'
working_dir: '/data/swamyvs/eyeintegration_splicing'
deeptools_version: 'deeptools/3.1.3'
mosdepth_version: 'mosdepth/0.2.3'
bedtools_version: 'bedtools/2.27.1'
