refGTF_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.annotation.gtf.gz'
refGFF3_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.basic.annotation.gff3.gz'
ref_genome_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/GRCh38.primary_assembly.genome.fa.gz'
ref_tx_fasta_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.transcripts.fa.gz'
refProtSeq_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.pc_translations.fa.gz'
ensembl_gtf_url: 'ftp://ftp.ensembl.org/pub/release-95/gtf/homo_sapiens/Homo_sapiens.GRCh38.95.gtf.gz'
refseq_ncbi_url: 'ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.gff.gz'
salmon_version: 'salmon/0.11.0'
stringtie_version: 'stringtie/1.3.4d'
STAR_version: 'STAR/2.6.1c'
rmats_verson: 'rmats/4.0.2'
R_version: 'R/3.5.0'
TransDecoder_version: 'TransDecoder/5.0.1'
samtools_version: 'samtools/1.9'
gffcompare_version: 'gffcompare/0.10.5'
sampleFile: 'sampleTableDev.tsv'
tissueFile: 'ref/tissues_dev.txt'
subtissueFile: 'ref/subtissues_dev.txt'
fastq_path: '/data/OGVFB_BG/EiaD_2019_05/'
bam_path: '/data/swamyvs/eyeintegration_splicing/'
working_dir: '/data/swamyvs/dev_eyeintegration_splicing/'
mosdepth_version: 'mosdepth/0.2.3'
bedtools_version: 'bedtools/2.27.1'
window_size: '40'
python_env: 'esp_pyenv_biowulf'
