---
title: "Gffcompare vs salmon quant"
output: html_notebook
---

```{r setup}
knitr::opts_knit$set(root.dir = '~/NIH/eyeintegration_splicing/')
#knitr::opts_knit$set(root.dir = '/data/swamyvs/eyeintegration_splicing/')
```


```{r}
library(tidyverse)
load('rdata/salmon_all_tissues_quant.Rdata')
sample_table <- read_tsv('sampleTableDev.tsv', col_names=c('sample', 'run', 'paired', 'tissue', 'subtissue', 'origin'))
gff_tracking_file <- read_tsv('testing/all_tissues.tracking', col_names = F) %>% select(-X3, -X4)
tissues <- unique(sample_table$subtissue)
nm_col <- function(col){
    keep <- sapply(tissues, function(x) any(grepl(x, col)))
    return(tissues[keep])
}
names <- c('transcript_id', 'gene_id',  apply(gff_tracking_file[,-(1:2)], 2, nm_col))
colnames(gff_tracking_file) <- names
detected_by_gffcompare <-  gff_tracking_file[,-(1:2)] %>% mutate_all(function(x) x!='-') %>% 
    cbind(gff_tracking_file[,1:2], .) %>% 
    select(-gene_id) %>% 
    arrange(transcript_id)

det.quant <- function(t){
    filter(sample_table, subtissue == t) %>% pull(sample) %>% {counts[,.]} %>% {rowSums(.) >=ncol(.)}
}
detected_by_salmon <- lapply(tissues, det.quant) %>% bind_cols %>% cbind(counts[,1], .) 
colnames(detected_by_salmon) <- c('transcript_id', tissues)
detected_by_salmon <- detected_by_salmon %>% arrange(transcript_id)
detected_by_gffcompare <- detected_by_gffcompare[,colnames(detected_by_salmon)]

sapply(tissues, function(col) sum(detected_by_gffcompare[,col] == detected_by_salmon[,col]) / nrow(detected_by_salmon) )
    
sapply(tissues, function(col) sum(detected_by_gffcompare[,col]) - sum(detected_by_salmon[,col])  )    
```



```{r}

```



